### ISSUE TITLE
admin ressources...for registration!

### ISSUE THREAD

**Issue by odyright** [shankardevy/mango#5]
@shankardevy nice work, I appreciated what you achieve. I just started to learn elixir, and I want to know something, in your "e-commerce" project if the **Admin** want to create / register a customer himself, should we have to share the same "**register_controller**" between admin route & frontend route? if yes how to specify the "conditional" code now?

I'm aware that in practice that isn't the case with ecommerce project...but it's most like educational systems (where students can register themselves & the admin can register a student).

**Comment by shankardevy** [comment]
@odyright thanks for your comments. Regarding your question, I would create a new controller for registering 'students' by the admin user. Since controllers in Phoenix 1.3 are very lean and all hard work is moved to the context modules, you are not going to duplicate code by creating a new controller for registering students.

Hope it helps. Let me know if you still have any questions.
